CREATE DATABASE IF NOT EXISTS ELETRODOMESTICOS_SAEP_DB;
USE ELETRODOMESTICOS_SAEP_DB;

CREATE TABLE USUARIO (
    USU_ID INT AUTO_INCREMENT PRIMARY KEY,
    USU_NOME VARCHAR(255) NOT NULL,
    USU_EMAIL VARCHAR(255) UNIQUE NOT NULL,
    USU_SENHA VARCHAR(255) NOT NULL
);

CREATE TABLE LOG (
    LOG_ID INT AUTO_INCREMENT PRIMARY KEY,
    LOG_DESCRICAO VARCHAR(255),
    LOG_DATA_HORA DATETIME DEFAULT CURRENT_TIMESTAMP,
    FK_USU_ID INT,
    FOREIGN KEY (FK_USU_ID) REFERENCES USUARIO(USU_ID) ON DELETE CASCADE
);

CREATE TABLE ELETRODOMESTICO (
    ELETRODOMESTICO_ID INT AUTO_INCREMENT PRIMARY KEY,
    ELETRODOMESTICO_NOME VARCHAR(255) NOT NULL,
    ELETRODOMESTICO_QTD_ESTOQUE INT DEFAULT 0,
    ELETRODOMESTICO_FORNECEDOR VARCHAR(255),
    ELETRODOMESTICO_CATEGORIA VARCHAR(255),
    ELETRODOMESTICO_POTENCIA FLOAT,
    ELETRODOMESTICO_CONS_ENER FLOAT,
    ELETRODOMESTICO_GARANTIA VARCHAR(255),
    ELETRODOMESTICO_PRIOR_REP VARCHAR(255),
    FK_USU_ID INT,
    FOREIGN KEY (FK_USU_ID) REFERENCES USUARIO(USU_ID) ON DELETE CASCADE
);

CREATE TABLE ESTOQUE (
    ESTOQUE_ID INT AUTO_INCREMENT PRIMARY KEY,
    ESTOQUE_QTD INT NOT NULL,
    FK_ELETRODOMESTICO_ID INT,
    FOREIGN KEY (FK_ELETRODOMESTICO_ID) REFERENCES ELETRODOMESTICO(ELETRODOMESTICO_ID) ON DELETE CASCADE
);

-- NOVOS USUÁRIOS
INSERT INTO USUARIO (USU_EMAIL, USU_SENHA, USU_NOME)
VALUES 
('carlos.souza@email.com', 'senha123', 'Carlos Souza'),
('mariana.silva@email.com', 'abc98765', 'Mariana Silva'),
('ricardo.lima@email.com', 'qwerty12', 'Ricardo Lima');

-- NOVOS ELETRODOMÉSTICOS
INSERT INTO ELETRODOMESTICO 
(ELETRODOMESTICO_NOME, ELETRODOMESTICO_QTD_ESTOQUE, ELETRODOMESTICO_FORNECEDOR, ELETRODOMESTICO_CATEGORIA, ELETRODOMESTICO_POTENCIA, ELETRODOMESTICO_CONS_ENER, ELETRODOMESTICO_GARANTIA, ELETRODOMESTICO_PRIOR_REP, FK_USU_ID)
VALUES 
('Aspirador de Pó 2000W', 10, 'Mondial', 'Limpeza', 2000.00, 18, '18 meses', 'Média', 1),
('Ventilador de Coluna 50cm', 25, 'Arno', 'Climatização', 120.00, 8, '12 meses', 'Baixa', 2),
('Máquina de Lavar 12kg', 5, 'Consul', 'Lavanderia', 1500.00, 28, '24 meses', 'Alta', 3);

-- ESTOQUE ATUALIZADO
INSERT INTO ESTOQUE (ESTOQUE_QTD, FK_ELETRODOMESTICO_ID)
VALUES 
(10, 1),
(25, 2),
(5, 3);

-- Verificação
SELECT * FROM ELETRODOMESTICO;
